import React from "react";
import type { Metadata } from "next";

import Lenis from "@/components/Lenis";
import Header from "@/components/Header";

import "@/styles/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Lenis>{children}</Lenis>
      </body>
    </html>
  );
}
